modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="vampire_era"
version="1.0.0"
displayName="Vampire Era"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Jaie55, LauSenpai"
description="vanpiro esistein"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.vampire_era]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



